import { Inter } from "next/font/google";

import Providers from "./redux/Providers";

import "@styles/globals.css";

import Header from "@components/Header";
import Footer from "@components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link
          href="/vendor/icons/css/materialdesignicons.min.css"
          media="all"
          rel="stylesheet"
          type="text/css"
        />
        <link href="/vendor/unicons-2.0.1/css/unicons.css" rel="stylesheet" />
        <link
          rel="stylesheet"
          type="text/css"
          href="/vendor/semantic/semantic.min.css"
        />
      </head>
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
        <script src="/vendor/jquery/jquery.min.js"></script>
        <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="/js/custom.js"></script>
        <script src="/js/offset_overlay.js"></script>
      </body>
    </html>
  );
}
